AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'script/**/*'
    - 'vendor/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'spec/unit/**/*'
    - 'spec/integration/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/active_fedora/datastreams/nokogiri_datastreams.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/active_fedora/datastreams/nokogiri_datastreams.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/active_fedora/rdf/rdf_datastream.rb'
    - 'lib/active_fedora/qualified_dublin_core_datastream.rb'
    - 'spec/samples/hydra-mods_article_datastream.rb'

Metrics/MethodLength:
  Enabled: false

Style/PredicateName:
  Exclude:
    - 'lib/active_fedora/om_datastream.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/Semicolon:
  Exclude:
    - 'spec/**/*'

Style/Lambda:
  Exclude:
    - 'spec/**/*'
    
Style/FileName:
  Exclude:
    - 'spec/samples/hydra-mods_article_datastream.rb'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/NotToNot:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false